### ISSUE TITLE
🔥 Review high CPU (docker/macOS) #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [jpdillingham/Soulseek.NET#318]
Heeeey,

Hope you're well

Thanks for sick software

As title

Usually, all my docker processes idle at ~50% CPU (whatever that means)

When I start my soulseek container it blasts up to >100% then when I run a search it's up at ~200%. I have observed it going >400% earlier today; inspecting logs I presume when peer connection(s) happen.

This is very high CPU for me

```
version: '3'
services:

  soulseek:
    environment:
      - SLSK_CONNECT_TIMEOUT=5000
      - SLSK_DIAGNOSTIC=Info
      - SLSK_DNET_CHILD_LIMIT=10
      - SLSK_ENABLE_DNET=true
      - SLSK_INACTIVITY_TIMEOUT=15000
      - SLSK_LISTEN_PORT=50000
      - SLSK_PASSWORD=obfuscated
      - SLSK_USERNAME=obfuscated
    image: jpdillingham/slsk-web-example:latest
    ports:
      - 50000:50000
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ~/Downloads/-data/soulseek/download:/var/slsk/download
      - ~/Downloads/-data/soulseek/share:/var/slsk/shared
```

Anyone else experiencing this?:

* If yes then I think this got introduced in the [latest release] because I haven't experienced it until lately

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up super work!

Hope this helps & to hear back

Sincerely

hardware: Apple, MacBook Pro (16-inch, 2019)
software - operating system: Apple, macOS, 10.15.4 (19E287)
software - application: soulseek, 1.0.0-rc2

docker: stable 19.03.8 (bottled)
docker-compose: stable 1.25.5 (bottled), HEAD

[latest release]: https://github.com/jpdillingham/Soulseek.NET/releases/tag/1.0.0-rc2
